export const SOCKET_PUBLISHER_PUBLISH_ACTION =
  'app/containers/Socket/PUBLISHER_PUBLISH_ACTION';
export const SOCKET_PUBLISHER_PUBLISH_ACTION_FAILURE =
  'app/containers/Socket/PUBLISHER_PUBLISH_ACTION_FAILURE';
export const SOCKET_PUBLISHER_PUBLISH_ACTION_SUCCESS =
  'app/containers/Socket/PUBLISHER_PUBLISH_ACTION_SUCCESS';

export const SOCKET_PUBLISHER_PUBLISH_SESSION =
  'app/containers/Socket/PUBLISHER_PUBLISH_SESSION';
export const SOCKET_PUBLISHER_PUBLISH_SESSION_FAILURE =
  'app/containers/Socket/PUBLISHER_PUBLISH_SESSION_FAILURE';
export const SOCKET_PUBLISHER_PUBLISH_SESSION_SUCCESS =
  'app/containers/Socket/PUBLISHER_PUBLISH_SESSION_SUCCESS';

export const SOCKET_PUBLISHER_PUBLISH_USER =
  'app/containers/Socket/PUBLISHER_PUBLISH_USER';
export const SOCKET_PUBLISHER_PUBLISH_USER_FAILURE =
  'app/containers/Socket/PUBLISHER_PUBLISH_USER_FAILURE';
export const SOCKET_PUBLISHER_PUBLISH_USER_SUCCESS =
  'app/containers/Socket/PUBLISHER_PUBLISH_USER_SUCCESS';

export const SOCKET_PUBLISHER_RECEIVE_ACTION =
  'app/containers/Socket/PUBLISHER_RECEIVE_ACTION';
export const SOCKET_PUBLISHER_RECEIVE_USER =
  'app/containers/Socket/PUBLISHER_RECEIVE_USER';

export const SOCKET_PUBLISHER_SUBSCRIBE_ACTIONS =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_ACTIONS';
export const SOCKET_PUBLISHER_SUBSCRIBE_ACTIONS_FAILURE =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_ACTIONS_FAILURE';
export const SOCKET_PUBLISHER_SUBSCRIBE_ACTIONS_SUCCESS =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_ACTIONS_SUCCESS';

export const SOCKET_PUBLISHER_SUBSCRIBE_USERS =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_USERS';
export const SOCKET_PUBLISHER_SUBSCRIBE_USERS_FAILURE =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_USERS_FAILURE';
export const SOCKET_PUBLISHER_SUBSCRIBE_USERS_SUCCESS =
  'app/containers/Socket/PUBLISHER_SUBSCRIBE_USERS_SUCCESS';

export const SOCKET_PUBLISHER_UNPUBLISH_SESSION =
  'app/containers/Socket/PUBLISHER_UNPUBLISH_SESSION';
export const SOCKET_PUBLISHER_UNPUBLISH_SESSION_FAILURE =
  'app/containers/Socket/PUBLISHER_UNPUBLISH_SESSION_FAILURE';
export const SOCKET_PUBLISHER_UNPUBLISH_SESSION_SUCCESS =
  'app/containers/Socket/PUBLISHER_UNPUBLISH_SESSION_SUCCESS';
