export const SOCKET_SUBSCRIBER_PUBLISH_USER =
  'app/containers/Socket/SUBSCRIBER_PUBLISH_USER';
export const SOCKET_SUBSCRIBER_PUBLISH_USER_FAILURE =
  'app/containers/Socket/SUBSCRIBER_PUBLISH_USER_FAILURE';
export const SOCKET_SUBSCRIBER_PUBLISH_USER_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_PUBLISH_USER_SUCCESS';

export const SOCKET_SUBSCRIBER_RECEIVE_SESSION =
  'app/containers/Socket/SUBSCRIBER_RECEIVE_SESSION';
export const SOCKET_SUBSCRIBER_RECEIVE_USER =
  'app/containers/Socket/SUBSCRIBER_RECEIVE_USER';

export const SOCKET_SUBSCRIBER_SUBSCRIBE_ACTIONS =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_ACTIONS';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_ACTIONS_FAILURE =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_ACTIONS_FAILURE';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_ACTIONS_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_ACTIONS_SUCCESS';

export const SOCKET_SUBSCRIBER_SUBSCRIBE_SESSION =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_SESSION';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_SESSION_FAILURE =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_SESSION_FAILURE';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_SESSION_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_SESSION_SUCCESS';

export const SOCKET_SUBSCRIBER_SUBSCRIBE_USERS =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_USERS';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_USERS_FAILURE =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_USERS_FAILURE';
export const SOCKET_SUBSCRIBER_SUBSCRIBE_USERS_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_SUBSCRIBE_USERS_SUCCESS';

export const SOCKET_SUBSCRIBER_UNPUBLISH_USER =
  'app/containers/Socket/SUBSCRIBER_UNPUBLISH_USER';
export const SOCKET_SUBSCRIBER_UNPUBLISH_USER_FAILURE =
  'app/containers/Socket/SUBSCRIBER_UNPUBLISH_USER_FAILURE';
export const SOCKET_SUBSCRIBER_UNPUBLISH_USER_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_UNPUBLISH_USER_SUCCESS';

export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_ACTIONS =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_ACTIONS';
export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_ACTIONS_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_ACTIONS_SUCCESS';
export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_ACTIONS_FAILURE =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_ACTIONS_FAILURE';

export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_USERS =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_USERS';
export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_USERS_SUCCESS =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_USERS_SUCCESS';
export const SOCKET_SUBSCRIBER_UNSUBSCRIBE_USERS_FAILURE =
  'app/containers/Socket/SUBSCRIBER_UNSUBSCRIBE_USERS_FAILURE';
