export const WEBSOCKET_CONNECTOR_SESSION_ACTION_RECEIVED =
  'app/containers/WebsocketConnector/SESSION_ACTION_RECEIVED';
export const WEBSOCKET_CONNECTOR_SESSION_ACTION_SENT =
  'app/containers/WebsocketConnector/SESSION_ACTION_SENT';

export const WEBSOCKET_CONNECTOR_PUBLISH_SESSION =
  'app/containers/WebsocketConnector/PUBLISH_SESSION';
export const WEBSOCKET_CONNECTOR_PUBLISH_SESSION_FAILURE =
  'app/containers/WebsocketConnector/PUBLISH_SESSION_FAILURE';
export const WEBSOCKET_CONNECTOR_PUBLISH_SESSION_SUCCESS =
  'app/containers/WebsocketConnector/PUBLISH_SESSION_SUCCESS';

export const WEBSOCKET_CONNECTOR_UNPUBLISH_SESSION =
  'app/containers/WebsocketConnector/UNPUBLISH_SESSION';
export const WEBSOCKET_CONNECTOR_UNPUBLISH_SESSION_FAILURE =
  'app/containers/WebsocketConnector/UNPUBLISH_SESSION_FAILURE';
export const WEBSOCKET_CONNECTOR_UNPUBLISH_SESSION_SUCCESS =
  'app/containers/WebsocketConnector/UNPUBLISH_SESSION_SUCCESS';

export const WEBSOCKET_CONNECTOR_PUBLISH_ACTION =
  'app/containers/WebsocketConnector/PUBLISH_ACTION';
export const WEBSOCKET_CONNECTOR_PUBLISH_ACTION_FAILURE =
  'app/containers/WebsocketConnector/PUBLISH_ACTION_FAILURE';
export const WEBSOCKET_CONNECTOR_PUBLISH_ACTION_SUCCESS =
  'app/containers/WebsocketConnector/PUBLISH_ACTION_SUCCESS';

export const WEBSOCKET_CONNECTOR_PUBLISH_USER =
  'app/containers/WebsocketConnector/PUBLISH_USER';
export const WEBSOCKET_CONNECTOR_PUBLISH_USER_FAILURE =
  'app/containers/WebsocketConnector/PUBLISH_USER_FAILURE';
export const WEBSOCKET_CONNECTOR_PUBLISH_USER_SUCCESS =
  'app/containers/WebsocketConnector/PUBLISH_USER_SUCCESS';
export const WEBSOCKET_CONNECTOR_PUBLISH_USER_SUCCESS_FROM_WEBSOCKET =
  'app/containers/WebsocketConnector/PUBLISH_USER_SUCCESS_FROM_WEBSOCKET';

export const WEBSOCKET_CONNECTOR_UNPUBLISH_USER =
  'app/containers/WebsocketConnector/UNPUBLISH_USER';
export const WEBSOCKET_CONNECTOR_UNPUBLISH_USER_FAILURE =
  'app/containers/WebsocketConnector/UNPUBLISH_USER_FAILURE';
export const WEBSOCKET_CONNECTOR_UNPUBLISH_USER_SUCCESS =
  'app/containers/WebsocketConnector/UNPUBLISH_USER_SUCCESS';

export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_FAILURE =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_FAILURE';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_SUCCESS =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_SUCCESS';

export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_FAILURE =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_FAILURE';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_SUCCESS =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_SUCCESS';

export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_ACTIONS =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_ACTIONS';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_ACTIONS_FAILURE =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_ACTIONS_FAILURE';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_ACTIONS_SUCCESS =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_ACTIONS_SUCCESS';

export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_ACTIONS =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_ACTIONS';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_ACTIONS_FAILURE =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_ACTIONS_FAILURE';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_ACTIONS_SUCCESS =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_ACTIONS_SUCCESS';

export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_USERS =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_USERS';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_USERS_FAILURE =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_USERS_FAILURE';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_USERS_SUCCESS =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_USERS_SUCCESS';
export const WEBSOCKET_CONNECTOR_SUBSCRIBE_TO_SESSION_USERS_FROM_WEBSOCKET =
  'app/containers/WebsocketConnector/SUBSCRIBE_TO_SESSION_USERS_FROM_WEBSOCKET';

export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_USERS =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_USERS';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_USERS_FAILURE =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_USERS_FAILURE';
export const WEBSOCKET_CONNECTOR_UNSUBSCRIBE_SESSION_USERS_SUCCESS =
  'app/containers/WebsocketConnector/UNSUBSCRIBE_SESSION_USERS_SUCCESS';

export const WEBSOCKET_CONNECTOR_CONNECT =
  'app/containers/WebsocketConnector/CONNECT';
export const WEBSOCKET_CONNECTOR_CONNECT_FROM_WEBSOCKET =
  'app/containers/WebsocketConnector/CONNECT_FROM_WEBSOCKET';
export const WEBSOCKET_CONNECTOR_DISCONNECT =
  'app/containers/WebsocketConnector/DISCONNECT';
export const WEBSOCKET_CONNECTOR_DISCONNECT_FROM_WEBSOCKET =
  'app/containers/WebsocketConnector/DISCONNECT_FROM_WEBSOCKET';
export const WEBSOCKET_CONNECTOR_RESET =
  'app/containers/WebsocketConnector/RESET';

// Input field action types
export const WEBSOCKET_CONNECTOR_USERNAME_ONCHANGE =
  'app/containers/WebsocketConnector/USERNAME_ONCHANGE';
export const WEBSOCKET_CONNECTOR_TOPIC_ONCHANGE =
  'app/containers/WebsocketConnector/TOPIC_ONCHANGE';
